///|
const OP_NOP : Byte = 0

///|
const OP_RETURN : Byte = 1

///|
const OP_PRINT : Byte = 2

///|
const OP_POP : Byte = 3

///|
const OP_DEFINE_GLOBAL : Byte = 4

///|
const OP_GET_GLOBAL : Byte = 5

///|
const OP_SET_GLOBAL : Byte = 6

///|
const OP_GET_LOCAL : Byte = 7

///|
const OP_SET_LOCAL : Byte = 8

///|
const OP_GET_UPVALUE : Byte = 9

///|
const OP_SET_UPVALUE : Byte = 10

///|
const OP_GET_PROPERTY : Byte = 11

///|
const OP_SET_PROPERTY : Byte = 12

///|
const OP_GET_SUPER : Byte = 13

///|
const OP_JUMP_IF_FALSE : Byte = 20

///|
const OP_JUMP : Byte = 21

///|
const OP_LOOP : Byte = 22

///|
const OP_CALL : Byte = 23

///|
const OP_CLOSURE : Byte = 24

///|
const OP_CLOSE_UPVALUE : Byte = 25

///|
const OP_CLASS : Byte = 26

///|
const OP_METHOD : Byte = 27

///|
const OP_INVOKE : Byte = 28

///|
const OP_SUPER_INVOKE : Byte = 29

///|
const OP_INHERIT : Byte = 30

///|
const OP_CONSTANT : Byte = 51

///|
const OP_NIL : Byte = 52

///|
const OP_TRUE : Byte = 53

///|
const OP_FALSE : Byte = 54

///|
const OP_EQUAL : Byte = 55

///|
const OP_GREATER : Byte = 56

///|
const OP_LESS : Byte = 57

///|
const OP_NEGATE : Byte = 58

///|
const OP_NOT : Byte = 59

///|
const OP_ADD : Byte = 60

///|
const OP_SUBTRACT : Byte = 61

///|
const OP_MULTIPLY : Byte = 62

///|
const OP_DIVIDE : Byte = 63

///|
const OP_MOD : Byte = 64
